name: yolov4-gpu

dependencies:
  - python
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit
  - pip:
    - tensorflow-gpu
    - opencv-python
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
